# Author: James Ashmore
# Copyright: Copyright 1010, James Ashmore
# Email: jashmore@ed.ac.uk
# License: MIT

configfile: "config/config.yml"

MODELS = ["modelGeneVar", "modelGeneCV2", "modelGeneVarByPoisson"]

METRICS = ["sum", "detected"]

rule all:
    input:
        # Droplet processing
        "analysis/droplet-processing/barcodeRanks.rds",
        "analysis/droplet-processing/barcodeRanksPlot.pdf",
        "analysis/droplet-processing/emptyDrops.rds",
        "analysis/droplet-processing/emptyDrops.ambient.rds",
        "analysis/droplet-processing/emptyDropsLogProb.pdf",
        "analysis/droplet-processing/emptyDropsPValue.pdf",
        "analysis/droplet-processing/emptyDropsRank.pdf",
        "analysis/droplet-processing/filterByDrops.rds",
        # # Quality control
        "analysis/quality-control/perCellQCMetrics.rds",
        "analysis/quality-control/quickPerCellQC.rds",
        "analysis/quality-control/plotCellQCMetrics.sum.pdf",
        "analysis/quality-control/plotCellQCMetrics.detected.pdf",
        "analysis/quality-control/plotCellQCMetrics.MT.pdf",
        "analysis/quality-control/plotCellQCMetrics.sum.MT.pdf",
        "analysis/quality-control/plotCellQCMetrics.sum.detected.pdf",
        "analysis/quality-control/filterCellsByQC.rds",
        "analysis/quality-control/perFeatureQCMetrics.rds",
        "analysis/quality-control/plotFeatureQCMetrics.mean.pdf",
        "analysis/quality-control/plotFeatureQCMetrics.detected.pdf",
        "analysis/quality-control/plotExprsFreqVsMean.pdf",
        "analysis/quality-control/plotHighestExprs.pdf",
        # # Normalization
        "analysis/normalization/librarySizeFactors.rds",
        "analysis/normalization/calculateSumFactors.rds",
        "analysis/normalization/logNormCounts.rds",
        # # Feature selection
        "analysis/feature-selection/modelGeneVar.rds",
        "analysis/feature-selection/modelGeneCV2.rds",
        "analysis/feature-selection/modelGeneVarByPoisson.rds",
        "analysis/feature-selection/plotGeneVar.pdf",
        "analysis/feature-selection/plotGeneCV2.pdf",
        "analysis/feature-selection/plotGeneVarByPoisson.pdf",
        "analysis/feature-selection/modelGeneVar.HVG.rds",
        "analysis/feature-selection/modelGeneCV2.HVG.rds",
        "analysis/feature-selection/modelGeneVarByPoisson.HVG.rds"

# Workflow rules
include: "rules/droplet-processing.smk"
include: "rules/quality-control.smk"
include: "rules/normalization.smk"
include: "rules/feature-selection.smk"
include: "rules/reduced-dimensions.smk"
include: "rules/clustering.smk"
include: "rules/doublet-detection.smk"
include: "rules/cell-cycle.smk"
include: "rules/marker-detection.smk"
include: "rules/cell-annotation.smk"
include: "rules/trajectory.smk"
