name: osca
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-annotationhub
  - bioconductor-aucell
  - bioconductor-basilisk
  - bioconductor-batchelor
  - bioconductor-biocfilecache
  - bioconductor-biocneighbors
  - bioconductor-biocparallel
  - bioconductor-biocsingular
  - bioconductor-biocstyle
  - bioconductor-delayedmatrixstats
  - bioconductor-dropletutils
  - bioconductor-edger
  - bioconductor-go.db
  - bioconductor-gseabase
  - bioconductor-isee
  - bioconductor-limma
  - bioconductor-org.mm.eg.db
  - bioconductor-pcatools
  - bioconductor-reactome.db
  - bioconductor-scater
  - bioconductor-scdblfinder
  - bioconductor-scran
  - bioconductor-singlecellexperiment
  - bioconductor-singler
  - bioconductor-slingshot
  - bioconductor-tradeseq
  - bioconductor-tscan
  - bioconductor-velociraptor
  - r-cluster
  - r-dendextend
  - r-dynamictreecut
  - r-ggbeeswarm
  - r-ggforce
  - r-gridextra
  - r-gtools
  - r-igraph
  - r-knitr
  - r-magick
  - r-matrix
  - r-msigdbr
  - r-patchwork
  - r-pdftools
  - r-pheatmap
  - r-rmtstat
  - r-robustbase
  - r-rtsne
  - r-statmod
  - r-uwot
  - r-viridis